### ISSUE TITLE
0.8.0 fails to build on NetBSD

### ISSUE THREAD

**Issue by 0323pin** [arxanas/git-branchless#1047]
### Description of the bug

0.8.0 fails to build on NetBSD using Rust-1.71.1 due to ioctl-rs

### Actual behavior

Compiling ioctl-rs v0.1.6
error[E0425]: cannot find function `ioctl` in this scope
  --> /usr/pkgsrc/wip/git-branchless/work/vendor/ioctl-rs-0.1.6/src/lib.rs:29:20
   |
29 |     match unsafe { ioctl(fd, TIOCEXCL) } {
   |                    ^^^^^ not found in this scope
   |
help: consider importing this function
   |
3  + use libc::ioctl;
   |

error[E0425]: cannot find value `TIOCEXCL` in this scope
  --> /usr/pkgsrc/wip/git-branchless/work/vendor/ioctl-rs-0.1.6/src/lib.rs:29:30
   |
29 |     match unsafe { ioctl(fd, TIOCEXCL) } {
   |                              ^^^^^^^^ not found in this scope
   |
help: consider importing this constant
   |
3  + use libc::TIOCEXCL;
   |

error[E0425]: cannot find function `ioctl` in this scope
  --> /usr/pkgsrc/wip/git-branchless/work/vendor/ioctl-rs-0.1.6/src/lib.rs:37:20
   |
37 |     match unsafe { ioctl(fd, TIOCNXCL) } {
   |                    ^^^^^ not found in this scope
   |
help: consider importing this function
   |
3  + use libc::ioctl;
   |

error[E0425]: cannot find value `TIOCNXCL` in this scope
  --> /usr/pkgsrc/wip/git-branchless/work/vendor/ioctl-rs-0.1.6/src/lib.rs:37:30
   |
37 |     match unsafe { ioctl(fd, TIOCNXCL) } {
   |                              ^^^^^^^^ not found in this scope
   |
help: consider importing this constant
   |
3  + use libc::TIOCNXCL;
   |

error[E0425]: cannot find function `ioctl` in this scope
  --> /usr/pkgsrc/wip/git-branchless/work/vendor/ioctl-rs-0.1.6/src/lib.rs:47:20
   |
47 |     match unsafe { ioctl(fd, TIOCMGET, &mut bits) } {
   |                    ^^^^^ not found in this scope
   |
help: consider importing this function
   |
3  + use libc::ioctl;
   |

error[E0425]: cannot find value `TIOCMGET` in this scope
  --> /usr/pkgsrc/wip/git-branchless/work/vendor/ioctl-rs-0.1.6/src/lib.rs:47:30
   |
47 |     match unsafe { ioctl(fd, TIOCMGET, &mut bits) } {
   |                              ^^^^^^^^ not found in this scope
   |
help: consider importing this constant
   |
3  + use libc::TIOCMGET;
   |

error[E0425]: cannot find function `ioctl` in this scope
  --> /usr/pkgsrc/wip/git-branchless/work/vendor/ioctl-rs-0.1.6/src/lib.rs:55:20
   |
55 |     match unsafe { ioctl(fd, TIOCMSET, &bits) } {
   |                    ^^^^^ not found in this scope
   |
help: consider importing this function
   |
3  + use libc::ioctl;
   |

error[E0425]: cannot find value `TIOCMSET` in this scope
  --> /usr/pkgsrc/wip/git-branchless/work/vendor/ioctl-rs-0.1.6/src/lib.rs:55:30
   |
55 |     match unsafe { ioctl(fd, TIOCMSET, &bits) } {
   |                              ^^^^^^^^ not found in this scope
   |
help: consider importing this constant
   |
3  + use libc::TIOCMSET;
   |

error[E0425]: cannot find function `ioctl` in this scope
  --> /usr/pkgsrc/wip/git-branchless/work/vendor/ioctl-rs-0.1.6/src/lib.rs:63:20
   |
63 |     match unsafe { ioctl(fd, TIOCMBIS, &bits) } {
   |                    ^^^^^ not found in this scope
   |
help: consider importing this function
   |
3  + use libc::ioctl;
   |

error[E0425]: cannot find value `TIOCMBIS` in this scope
  --> /usr/pkgsrc/wip/git-branchless/work/vendor/ioctl-rs-0.1.6/src/lib.rs:63:30
   |
63 |     match unsafe { ioctl(fd, TIOCMBIS, &bits) } {
   |                              ^^^^^^^^ not found in this scope
   |
help: consider importing this constant
   |
3  + use libc::TIOCMBIS;
   |

error[E0425]: cannot find function `ioctl` in this scope
  --> /usr/pkgsrc/wip/git-branchless/work/vendor/ioctl-rs-0.1.6/src/lib.rs:71:20
   |
71 |     match unsafe { ioctl(fd, TIOCMBIC, &bits) } {
   |                    ^^^^^ not found in this scope
   |
help: consider importing this function
   |
3  + use libc::ioctl;
   |

error[E0425]: cannot find value `TIOCMBIC` in this scope
  --> /usr/pkgsrc/wip/git-branchless/work/vendor/ioctl-rs-0.1.6/src/lib.rs:71:30
   |
71 |     match unsafe { ioctl(fd, TIOCMBIC, &bits) } {
   |                              ^^^^^^^^ not found in this scope
   |
help: consider importing this constant
   |
3  + use libc::TIOCMBIC;
   |

For more information about this error, try `rustc --explain E0425`.
error: could not compile `ioctl-rs` (lib) due to 12 previous errors
warning: build failed, waiting for other jobs to finish...
*** Error code 101

Stop.
make[1]: stopped in /usr/pkgsrc/wip/git-branchless
*** Error code 1

Stop.

### Version of `rustc`

1.71.1

### Version of `git-branchless`

0.8.0

**Comment by 0323pin** [comment]
@arxanas The same issue as when 0.7.0 was released :(
https://github.com/arxanas/git-branchless/issues/842

**Comment by 0323pin** [comment]
@arxanas Cheers, I'll try patching `ioctl-rs` and `serial-rs` with the unmerged PRs and inject the [relevant support](https://raw.githubusercontent.com/dcuddeback/ioctl-rs/8ce409a15abb3c3f8e0bc45adbe09c14fb507817/src/os/netbsd.rs) 
See, https://github.com/dcuddeback/ioctl-rs/pull/5 and https://github.com/dcuddeback/serial-rs/pull/63

Hopefully, I won't hit version mismatch requiring further patches.

**Comment by arxanas** [comment]
@0323pin I don't plan to maintain forks myself, but, depending on how you're maintaining the NetBSD package, you can [use the existing forked repositories](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories) in [the `patch` section](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#using-patch-with-multiple-versions) of `Cargo.toml`.

**Comment by 0323pin** [comment]
> I don't plan to maintain forks myself,

I understand that.

> you can use the existing forked repositories in the patch section of Cargo.toml.

Yes, I'm aware of this and it's doable. It won't stop the bitrot, though. Those crates are not being updated.

Don't worry, I'll give it a thought and might consider an alternative solution.
