### ISSUE TITLE
Fails to build with rust 1.89.0

### ISSUE THREAD

**Issue by yurivict** [arxanas/git-branchless#1585]
### Description of the bug

```
error[E0308]: `match` arms have incompatible types
   --> /wrkdirs/usr/ports/devel/git-branchless/work/git-branchless-0.10.0/cargo-crates/esl01-indexedlog-0.3.0/src/lock.rs:138:30
    |
134 | /         match (opts.exclusive, opts.non_blocking) {
135 | |             (true, false) => file.lock_exclusive(),
    | |                              --------------------- this is found to be of type `std::result::Result<(), std::io::Error>`
136 | |             (true, true) => file.try_lock_exclusive(),
    | |                             ------------------------- this is found to be of type `std::result::Result<(), std::io::Error>`
137 | |             (false, false) => file.lock_shared(),
    | |                               ------------------ this is found to be of type `std::result::Result<(), std::io::Error>`
138 | |             (false, true) => file.try_lock_shared(),
    | |                              ^^^^^^^^^^^^^^^^^^^^^^ expected `Result<(), Error>`, found `Result<(), TryLockError>`
139 | |         }
    | |_________- `match` arms have incompatible types
```

[Downstream bug report](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=289015).

Version: 0.10.0
FreeBSD 14.3

**Comment by KudoLayton** [comment]
I think https://crates.io/crates/esl01-indexedlog crate causes the error.
The last commit of the crate has been done TWO YEARS ago

**Comment by claytonrcarter** [comment]
Thanks for the report. It looks like this has already been fixed upstream, but has not been released/published in a crate yet. I've opened https://github.com/facebook/sapling/issues/1119 to request an updated crate.

Until then, I'll note that our current MSRV is still 1.74: https://github.com/arxanas/git-branchless/blob/master/git-branchless/Cargo.toml#L14

**Comment by arxanas** [comment]
- For this specific case, I believe the maintained version of this crate is [`sapling-dag`](https://docs.rs/sapling-dag/latest/dag/). We should try migrating, but I believe there were some breakages that would need to be resolved.
- Generally, I don't recall if we had explicitly made the decision to specifically follow either `clap` or `jj`'s MSRV. `jj` probably makes sense?
- [tangential] It doesn't seem to help to run nightly Clippy on normal CI. It mostly blocks otherwise-passing CI runs. We should probably just drop it in favor of stable Clippy.

**Comment by tribbloid** [comment]
I'm on 1.90.0 (840b83a10 2025-07-30) toolchain and get the same problem

**Comment by vladfi1** [comment]
The docs should probably be updated to mention using rust 1.74 to install until this issue is resolved.

**Comment by BasixKOR** [comment]
Would it make sense to upstream the fixes from https://github.com/Homebrew/formula-patches/pull/1049 to here?

**Comment by arxanas** [comment]
I think this is resolved as of https://github.com/arxanas/git-branchless/releases/tag/v0.11.0? Please reopen if not.
